"""
HTML Exporter - Export reports as HTML documents
"""

import os
from datetime import datetime
from typing import Dict, List


class HTMLExporter:
    """Export security reports as HTML"""
    
    def __init__(self):
        self.style_template = self._get_style_template()
    
    def export(self, report_data: Dict, filepath: str) -> str:
        """Export report to HTML"""
        html_content = self._generate_html(report_data)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return filepath
    
    def _generate_html(self, report_data: Dict) -> str:
        """Generate HTML content from report data"""
        exec_summary = report_data.get('executive_summary', {})
        stats = report_data.get('statistics', {})
        findings = report_data.get('findings', [])
        recommendations = report_data.get('recommendations', [])
        
        html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{report_data.get('title', 'Security Report')}</title>
            <style>
                {self.style_template}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🔒 {report_data.get('title', 'Security Assessment Report')}</h1>
                    <p>Generated By: {report_data.get('generated_by', 'Unknown')}</p>
                    <p>Generated At: {report_data.get('generated_at', '')[:19]}</p>
                </div>
                
                <div class="section">
                    <h2>Executive Summary</h2>
                    <div class="summary-box">
                        <div class="risk-badge risk-{exec_summary.get('overall_risk', 'Low').lower()}">
                            Overall Risk: {exec_summary.get('overall_risk', 'Low')}
                        </div>
                        <p>{exec_summary.get('summary_text', 'No summary available')}</p>
                    </div>
                </div>
                
                <div class="section">
                    <h2>Statistics</h2>
                    <div class="stats-grid">
                        <div class="stat-card">
                            <div class="stat-value">{stats.get('total_scans', 0)}</div>
                            <div class="stat-label">Total Scans</div>
                        </div>
                        <div class="stat-card">
                            <div class="stat-value">{stats.get('total_findings', 0)}</div>
                            <div class="stat-label">Total Findings</div>
                        </div>
                        <div class="stat-card">
                            <div class="stat-value critical">{stats.get('critical', 0)}</div>
                            <div class="stat-label">Critical</div>
                        </div>
                        <div class="stat-card">
                            <div class="stat-value high">{stats.get('high', 0)}</div>
                            <div class="stat-label">High</div>
                        </div>
                        <div class="stat-card">
                            <div class="stat-value">{stats.get('risk_score', 0)}%</div>
                            <div class="stat-label">Risk Score</div>
                        </div>
                    </div>
                </div>
                
                <div class="section">
                    <h2>Detailed Findings</h2>
                    <div class="findings-list">
        """
        
        for finding in findings:
            severity = finding.get('severity', 'Low')
            html += f"""
                        <div class="finding finding-{severity.lower()}">
                            <div class="finding-header">
                                <span class="severity-badge severity-{severity.lower()}">{severity}</span>
                                <span class="finding-title">{finding.get('title', 'Untitled Finding')}</span>
                            </div>
                            <div class="finding-body">
                                <p><strong>Description:</strong> {finding.get('description', 'N/A')}</p>
                                <p><strong>Remediation:</strong> {finding.get('remediation', 'N/A')}</p>
                                <p><strong>Target:</strong> {finding.get('source_target', 'N/A')}</p>
                            </div>
                        </div>
            """
        
        html += """
                    </div>
                </div>
                
                <div class="section">
                    <h2>Recommendations</h2>
                    <div class="recommendations-list">
        """
        
        for rec in recommendations:
            html += f"""
                        <div class="recommendation">
                            <div class="rec-header">
                                <span class="priority-badge priority-{rec.get('priority', 'medium').lower()}">
                                    {rec.get('priority', 'Medium')}
                                </span>
                                <span>Timeline: {rec.get('timeline', 'N/A')}</span>
                            </div>
                            <ul>
            """
            for action in rec.get('actions', []):
                html += f"<li>{action}</li>"
            html += """
                            </ul>
                        </div>
            """
        
        html += """
                    </div>
                </div>
                
                <div class="footer">
                    <p>This report was automatically generated by RedTeamKa Enterprise Platform</p>
                    <p>Confidential - For authorized use only</p>
                </div>
            </div>
        </body>
        </html>
        """
        
        return html
    
    def _get_style_template(self) -> str:
        """Get CSS style template"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f5f5f5;
            padding: 40px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        
        .header {
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }
        
        .header h1 {
            margin-bottom: 10px;
        }
        
        .section {
            padding: 30px;
            border-bottom: 1px solid #e0e0e0;
        }
        
        .section h2 {
            color: #ff3366;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #ff3366;
        }
        
        .summary-box {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
        }
        
        .risk-badge {
            display: inline-block;
            padding: 8px 16px;
            border-radius: 4px;
            font-weight: bold;
            margin-bottom: 15px;
        }
        
        .risk-critical { background: #dc3545; color: white; }
        .risk-high { background: #fd7e14; color: white; }
        .risk-medium { background: #ffc107; color: #333; }
        .risk-low { background: #28a745; color: white; }
        
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }
        
        .stat-card {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            border-left: 4px solid #ff3366;
        }
        
        .stat-value {
            font-size: 32px;
            font-weight: bold;
            color: #333;
        }
        
        .stat-value.critical { color: #dc3545; }
        .stat-value.high { color: #fd7e14; }
        
        .stat-label {
            color: #666;
            margin-top: 5px;
        }
        
        .finding {
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            margin-bottom: 15px;
            overflow: hidden;
        }
        
        .finding-critical { border-left: 4px solid #dc3545; }
        .finding-high { border-left: 4px solid #fd7e14; }
        .finding-medium { border-left: 4px solid #ffc107; }
        .finding-low { border-left: 4px solid #28a745; }
        
        .finding-header {
            padding: 15px;
            background: #f8f9fa;
            border-bottom: 1px solid #e0e0e0;
            display: flex;
            align-items: center;
            gap: 15px;
        }
        
        .severity-badge {
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: bold;
        }
        
        .severity-critical { background: #dc3545; color: white; }
        .severity-high { background: #fd7e14; color: white; }
        .severity-medium { background: #ffc107; color: #333; }
        .severity-low { background: #28a745; color: white; }
        
        .finding-title {
            font-weight: bold;
            color: #333;
        }
        
        .finding-body {
            padding: 15px;
        }
        
        .finding-body p {
            margin: 10px 0;
        }
        
        .recommendation {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 15px;
        }
        
        .rec-header {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }
        
        .priority-badge {
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: bold;
        }
        
        .priority-critical { background: #dc3545; color: white; }
        .priority-high { background: #fd7e14; color: white; }
        .priority-medium { background: #ffc107; color: #333; }
        .priority-low { background: #28a745; color: white; }
        
        .recommendation ul {
            margin-left: 20px;
        }
        
        .recommendation li {
            margin: 5px 0;
        }
        
        .footer {
            padding: 20px;
            text-align: center;
            background: #f8f9fa;
            color: #666;
            font-size: 12px;
        }
        
        @media print {
            body {
                background: white;
                padding: 0;
            }
            .header {
                background: #1a1a2e;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
        """