"""
PDF Exporter - Export reports as PDF documents
"""

import os
from datetime import datetime
from typing import Dict, List
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT


class PDFExporter:
    """Export security reports as PDF"""
    
    def __init__(self, pagesize=A4):
        self.pagesize = pagesize
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a2e'),
            alignment=TA_CENTER,
            spaceAfter=30
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#ff3366'),
            spaceBefore=20,
            spaceAfter=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='SeverityCritical',
            parent=self.styles['Normal'],
            textColor=colors.HexColor('#dc3545'),
            fontSize=10,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='SeverityHigh',
            parent=self.styles['Normal'],
            textColor=colors.HexColor('#fd7e14'),
            fontSize=10,
            fontName='Helvetica-Bold'
        ))
    
    def export(self, report_data: Dict, filepath: str) -> str:
        """Export report to PDF"""
        doc = SimpleDocTemplate(
            filepath,
            pagesize=self.pagesize,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        story = []
        
        # Title
        story.append(Paragraph(report_data.get('title', 'Security Report'), self.styles['CustomTitle']))
        story.append(Spacer(1, 0.2 * inch))
        
        # Metadata
        story.append(Paragraph(f"Generated By: {report_data.get('generated_by', 'Unknown')}", self.styles['Normal']))
        story.append(Paragraph(f"Generated At: {report_data.get('generated_at', '')[:19]}", self.styles['Normal']))
        story.append(Spacer(1, 0.3 * inch))
        
        # Executive Summary
        story.append(Paragraph("Executive Summary", self.styles['CustomHeading']))
        exec_summary = report_data.get('executive_summary', {})
        story.append(Paragraph(exec_summary.get('summary_text', 'No summary available'), self.styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
        
        # Statistics Table
        story.append(Paragraph("Statistics", self.styles['CustomHeading']))
        stats = report_data.get('statistics', {})
        stats_data = [
            ['Metric', 'Value'],
            ['Total Scans', str(stats.get('total_scans', 0))],
            ['Total Findings', str(stats.get('total_findings', 0))],
            ['Critical Findings', str(stats.get('critical', 0))],
            ['High Findings', str(stats.get('high', 0))],
            ['Risk Score', f"{stats.get('risk_score', 0)}%"]
        ]
        
        stats_table = Table(stats_data, colWidths=[2.5 * inch, 1.5 * inch])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(stats_table)
        story.append(Spacer(1, 0.3 * inch))
        
        # Findings
        findings = report_data.get('findings', [])
        if findings:
            story.append(Paragraph("Detailed Findings", self.styles['CustomHeading']))
            
            for i, finding in enumerate(findings[:50], 1):  # Limit to 50 findings for PDF
                severity = finding.get('severity', 'Low')
                
                # Severity badge
                story.append(Paragraph(
                    f"Finding #{i}: {finding.get('title', 'Untitled')}",
                    self.styles[f'Severity{severity}'] if severity in ['Critical', 'High'] else self.styles['Normal']
                ))
                
                story.append(Paragraph(f"<b>Severity:</b> {severity}", self.styles['Normal']))
                story.append(Paragraph(f"<b>Description:</b> {finding.get('description', 'N/A')}", self.styles['Normal']))
                story.append(Paragraph(f"<b>Remediation:</b> {finding.get('remediation', 'N/A')}", self.styles['Normal']))
                story.append(Spacer(1, 0.1 * inch))
        
        # Recommendations
        recommendations = report_data.get('recommendations', [])
        if recommendations:
            story.append(PageBreak())
            story.append(Paragraph("Recommendations", self.styles['CustomHeading']))
            
            for rec in recommendations:
                story.append(Paragraph(f"<b>Priority: {rec.get('priority', 'Medium')}</b>", self.styles['Normal']))
                story.append(Paragraph(f"Timeline: {rec.get('timeline', 'N/A')}", self.styles['Normal']))
                for action in rec.get('actions', []):
                    story.append(Paragraph(f"• {action}", self.styles['Normal']))
                story.append(Spacer(1, 0.1 * inch))
        
        # Build PDF
        doc.build(story)
        
        return filepath