import json
import os
from datetime import datetime
from typing import List, Dict
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class ReportGenerator:
    def __init__(self):
        self.report_dir = "generated_reports"
        os.makedirs(self.report_dir, exist_ok=True)
    
    def generate_report(self, target: str, findings: List[Dict], credentials: List[Dict] = None) -> str:
        """Generate professional penetration test report"""
        
        report = f"""╔═══════════════════════════════════════════════════════════════════════════════╗
║                    RED TEAM PENETRATION TEST REPORT                                   ║
║                           CONFIDENTIAL DOCUMENT                                        ║
╚═══════════════════════════════════════════════════════════════════════════════════╝

Report ID: RT-{datetime.now().strftime('%Y%m%d-%H%M%S')}
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Target: {target}
Tester: Red Team Enterprise Framework
Classification: CONFIDENTIAL

{'=' * 70}

EXECUTIVE SUMMARY
{'-' * 40}

This report documents the findings of the authorized penetration test conducted against {target}.
The assessment utilized both automated and manual testing methodologies to identify
security vulnerabilities that could be exploited by malicious actors.

KEY FINDINGS
{'-' * 40}

Total Vulnerabilities Found: {len(findings)}
- Critical: {sum(1 for f in findings if f.get('severity', '').lower() == 'critical')}
- High: {sum(1 for f in findings if f.get('severity', '').lower() == 'high')}
- Medium: {sum(1 for f in findings if f.get('severity', '').lower() == 'medium')}
- Low: {sum(1 for f in findings if f.get('severity', '').lower() == 'low')}

Credentials Recovered: {len(credentials) if credentials else 0}

{'=' * 70}

DETAILED FINDINGS
{'-' * 40}

"""
        
        # Add detailed findings
        for i, finding in enumerate(findings, 1):
            report += f"""
┌─ FINDING #{i}
│
├─ Title: {finding.get('title', 'Untitled Finding')}
│
├─ Severity: {finding.get('severity', 'Medium').upper()}
│
├─ Description:
│  {finding.get('description', 'No description provided')}
│
├─ Impact:
│  {finding.get('impact', 'Not specified')}
│
├─ Remediation:
│  {finding.get('remediation', 'Apply security patches and follow best practices')}
│
└───────────────────────────────────────────────────────────────────

"""
        
        # Add credential section if exists
        if credentials:
            report += f"""
{'=' * 70}
COMPROMISED CREDENTIALS
{'-' * 40}

The following credentials were discovered during the assessment:

"""
            for cred in credentials:
                report += f"  • {cred.get('user', 'unknown')} : {cred.get('pass', 'unknown')}\n"
                report += f"    Source: {cred.get('source', 'manual')}\n"
                report += f"    Strength: {cred.get('strength', 'Unknown')}\n\n"
        
        # Add recommendations
        report += f"""
{'=' * 70}
RECOMMENDATIONS
{'-' * 40}

Priority 1 (Immediate):
{self._get_critical_recommendations(findings)}

Priority 2 (Short-term):
{self._get_high_recommendations(findings)}

Priority 3 (Long-term):
{self._get_general_recommendations()}

{'=' * 70}
TECHNICAL APPENDIX
{'-' * 40}

Testing Methodology:
• External Reconnaissance
• Port and Service Scanning  
• Vulnerability Assessment
• Exploitation Attempts
• Post-Exploitation Analysis
• Lateral Movement Testing
• Privilege Escalation Testing

Tools Used:
• Nmap - Port and service enumeration
• Metasploit Framework - Exploitation
• Custom scripts - Specialized testing
• Red Team Enterprise Framework - Orchestration

{'=' * 70}
CLASSIFICATION: CONFIDENTIAL
This report contains sensitive security information.
Distribution limited to authorized personnel only.

Report generated by: Red Team Enterprise Framework v2.0
Timestamp: {datetime.now().isoformat()}
{'=' * 70}
"""
        
        # Save report to file
        filename = f"{self.report_dir}/{target}_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        with open(filename, 'w') as f:
            f.write(report)
        
        logger.info(f"Report generated: {filename}")
        return filename
    
    def _get_critical_recommendations(self, findings: List[Dict]) -> str:
        """Get critical severity recommendations"""
        critical_findings = [f for f in findings if f.get('severity', '').lower() == 'critical']
        if critical_findings:
            return "\n".join([f"  • {f.get('title')}: {f.get('remediation', 'Patch immediately')}" for f in critical_findings[:3]])
        return "  • No critical findings - maintain current security posture"
    
    def _get_high_recommendations(self, findings: List[Dict]) -> str:
        """Get high severity recommendations"""
        high_findings = [f for f in findings if f.get('severity', '').lower() == 'high']
        if high_findings:
            return "\n".join([f"  • {f.get('title')}" for f in high_findings[:3]])
        return "  • Address high severity vulnerabilities within 30 days"
    
    def _get_general_recommendations(self) -> str:
        """Get general security recommendations"""
        return """  • Implement regular security awareness training
  • Conduct quarterly penetration tests
  • Deploy endpoint detection and response (EDR)
  • Implement principle of least privilege
  • Enable comprehensive logging and monitoring"""
    
    def generate_json_report(self, target: str, data: Dict) -> str:
        """Generate JSON format report for automation"""
        filename = f"{self.report_dir}/{target}_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        with open(filename, 'w') as f:
            json.dump(data, f, indent=2)
        return filename