/**
 * RedTeamKa - Reports Module
 */

const Reports = {
    /**
     * Load Reports View
     */
    async load() {
        const contentArea = document.getElementById('contentArea');
        if (!contentArea) return;
        
        contentArea.innerHTML = '<div class="loader"></div>';
        
        try {
            const reports = await RedTeamKa.apiGet('/reports');
            const scans = await RedTeamKa.apiGet('/scans');
            this.render(reports, scans);
        } catch (error) {
            contentArea.innerHTML = '<div class="error">Failed to load reports</div>';
        }
    },
    
    /**
     * Render Reports View
     */
    render(reports, scans) {
        const contentArea = document.getElementById('contentArea');
        const isPentest = RedTeamKa.isPentester();
        
        contentArea.innerHTML = `
            <div class="card">
                <div class="card-header">
                    <h2>Generate New Report</h2>
                </div>
                <div class="card-body">
                    <form id="generateReportForm">
                        <div class="form-group">
                            <label>Select Scans</label>
                            <select id="reportScans" multiple size="5">
                                ${scans.map(scan => `
                                    <option value="${scan.id}">${scan.target} - ${new Date(scan.created_at).toLocaleDateString()}</option>
                                `).join('')}
                            </select>
                            <small>Hold Ctrl/Cmd to select multiple scans</small>
                        </div>
                        <div class="form-group">
                            <label>Report Type</label>
                            <select id="reportType">
                                <option value="executive">Executive Summary</option>
                                <option value="technical">Technical Report</option>
                                <option value="full">Full Report</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Format</label>
                            <select id="reportFormat">
                                <option value="html">HTML</option>
                                <option value="pdf">PDF</option>
                                <option value="json">JSON</option>
                            </select>
                        </div>
                        <button type="submit" class="btn-primary">Generate Report</button>
                    </form>
                </div>
            </div>
            
            <div class="card">
                <div class="card-header">
                    <h2>Generated Reports</h2>
                </div>
                <div class="card-body">
                    <div class="scans-table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Type</th>
                                    <th>Format</th>
                                    <th>Generated By</th>
                                    <th>Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${reports.map(report => `
                                    <tr>
                                        <td>${report.title}</td>
                                        <td>${report.type}</td